---
name: CHIdeology
description: CHI 2026 Workshop on disentangling the fragmented politics, values and imaginaries of Human-Computer Interaction through ideologies
url: https://ideologies.digital
repository: https://github.com/uh-soco/digital-ideologies-www
site_branch: master

#remote_theme: broccolini/swiss
