---
name: CHIdeology
description: CHI 2026 Workshop on disentangling the fragmented politics, values and imaginaries of Human-Computer Interaction through ideologies
url: https://ideologies.digital
repository: https://github.com/uh-soco/digital-ideologies-www
site_branch: master

remote_theme: pages-themes/primer@v0.6.0

plugins:
  - jekyll-remote-theme